/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/**/*.{js,jsx,ts,tsx}',
    './src/**/**/*.{js,jsx,ts,tsx}',
    './src/**/**/**/*.{js,jsx,ts,tsx}',
  ],
  theme: {
    screens: {
      'sm': '500px',
      // => @media (min-width: 640px) { ... }

      'md': '768px',
      // => @media (min-width: 768px) { ... }

      'lg': '1024px',
      // => @media (min-width: 1024px) { ... }

      'xl': '1440px',
      // => @media (min-width: 1280px) { ... }

      '2xl': '1920px',
      // => @media (min-width: 1536px) { ... }
    },
    colors: {
      'transparent': 'transparent',
      'primary': 'var(--primary)',
      'on-primary': 'var(--on-primary)',
      'primary-container': 'var(--primary-container)',
      'on-primary-container': 'var(--on-primary-container)',
      'secondary': 'var(--secondary)',
      'on-secondary': 'var(--on-secondary)',
      'secondaryC-container': 'var(--secondary-container)',
      'on-secondary-container': 'var(--on-secondary-container)',
      'tertiary': 'var(--tertiary)',
      'on-tertiary': 'var(--on-tertiary)',
      'tertiary-container': 'var(--tertiary-container)',
      'on-tertiary-container': 'var(--on-tertiary-container)',
      'error': 'var(--error)',
      'on-error': 'var(--on-error)',
      'error-container': 'var(--error-container)',
      'on-error-container': 'var(--on-error-container)',
      'background': 'var(--background)',
      'on-background': 'var(--on-background)',
      'surface--variant': 'var(--surface--variant)',
      'on-surface--variant': 'var(--on-surface--variant)',
      'outline': 'var(--outline)',
      'surface-1': 'var(--surface-1)',
      'surface-2': 'var(--surface-2)',
      'surface-3': 'var(--surface-3)',
      'surface-4': 'var(--surface-4)',
      'surface-5': 'var(--surface-5)',
      'navigation': 'var(--navigation-bar)',
      'text-helper': '#5E6368',
      'disabled': 'var(--disabled)',
    },
    fontFamily: {
      sans: ['Source Sans Pro', 'sans-serif'],
      serif: ['Merriweather', 'serif'],
    },
    fontSize: {
      'body-sm': '12px',
      'body-md': '14px',
      'body-lg': '16px',
      'label-sm': '11px',
      'label-md': '12px',
      'label-lg': '14px',
      'title-sm': '14px',
      'title-md': '16px',
      'title-lg': '22px',
      'heading-sm': '24px',
      'heading-md': '28px',
      'heading-lg': '32px',
      'display-sm': '36px',
      'display-md': '45px',
      'display-lg': '57px',
    },
    fontWeight: {
      'hairline': 100,
      'extra-light': 100,
      'thin': 200,
      'light': 300,
      'normal': 400,
      'medium': 500,
      'semibold': 600,
      'bold': 700,
      'extrabold': 800,
      'extra-bold': 800,
      'black': 900,
    },
    borderRadius: {
      'none': '0',
      'sm': '2px',
      'DEFAULT': '4px',
      'md': '6px',
      'lg': '8px',
      'xl': '12px',
      '2xl': '16px',
      '3xl': '24px',
      'full': '9999px',
      'large': '12px',
    },
  },
  plugins: [],
};
